In [2]:
df = pd.read_csv("C:/Users/Admin/Desktop/Mutual_Fund_Analysis/data/raw/02_nav_history.csv")

In [3]:
df.head()

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

In [4]:
df.isna().sum()

amfi_code    0
date         0
nav          0
dtype: int64

In [5]:
import pandas as pd

nav = pd.read_csv("C:/Users/Admin/Desktop/Mutual_Fund_Analysis/data/raw/02_nav_history.csv")

# date
nav['date'] = pd.to_datetime(nav['date'])

# sort
nav = nav.sort_values(['amfi_code','date'])

# forward fill nav
nav['nav'] = nav.groupby('amfi_code')['nav'].ffill()

# remove duplicates
nav = nav.drop_duplicates()

# nav > 0
nav = nav[nav['nav'] > 0]

nav.to_csv(
    "C:/Users/Admin/Desktop/Mutual_Fund_Analysis/data/processed/02_nav_history.csv",
    index=False
)

In [6]:
df1 = pd.read_csv("C:/Users/Admin/Desktop/Mutual_Fund_Analysis/data/processed/02_nav_history.csv")
df1.head()

   amfi_code        date       nav
0     100016  2022-01-03  520.4608
1     100016  2022-01-04  515.0971
2     100016  2022-01-05  521.7239
3     100016  2022-01-06  515.7880
4     100016  2022-01-07  515.1639

In [2]:
import pandas as pd
df = pd.read_csv("C:/Users/Admin/Desktop/Mutual_Fund_Analysis/data/raw/08_investor_transactions.csv")

In [3]:
df["transaction_type"].unique()

array(['SIP', 'Redemption', 'Lumpsum'], dtype=object)

In [4]:
df.isnull().sum()

investor_id           0
transaction_date      0
amfi_code             0
transaction_type      0
amount_inr            0
state                 0
city                  0
city_tier             0
age_group             0
gender                0
annual_income_lakh    0
payment_mode          0
kyc_status            0
dtype: int64

In [5]:
df.duplicated().sum()

0

In [11]:
df["kyc_status"].value_counts()

kyc_status
Verified    30146
Pending      2632
Name: count, dtype: int64

In [12]:
df = df = pd.read_csv("C:/Users/Admin/Desktop/Mutual_Fund_Analysis/data/raw/04_monthly_sip_inflows.csv")

In [19]:
df.tail()

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
43,2025-08,28265,8.85,9.80,15.18,20.04
44,2025-09,29361,9.00,10.50,15.38,19.80
45,2025-10,29529,9.10,9.45,15.55,16.61
46,2025-11,30200,9.20,9.10,15.72,19.27
47,2025-12,31002,9.35,9.80,15.90,17.17